### ISSUE TITLE
Failed to initialise plugin at Startup 

### ISSUE THREAD

**Issue by kky-fury** [score-p/scorep_plugin_x86_energy#6]
During metric initialization the plugin reports:

`Score-P x86_energy_sync plugin: [i20r01c03s01][1645693135606721][FATAL]: Couldn't get the available mechanism.`
and fails to get initialized even when required enviornment variables are mentioned.

More information in job_testing_ptf_wo_scorep_debug.out (50-52) and job_testing_ptf_w_scorep_debug.out (505-520) in the zip file.

[plugin_outputs.zip](https://github.com/score-p/scorep_plugin_x86_energy/files/2197320/plugin_outputs.zip)

**Comment by AndreasGocht** [comment]
Hey,

seems like `x86_energy_get_avail_mechanism()` returns `NULL`. There are plenty of reasons why this might happen.

@rschoene Do you have an Idee, why NULL is returned in this case?

Best,

Andreas

**Comment by rschoene** [comment]
Dear @kky-fury, I pushed changes to the mohak_debug branch of https://github.com/tud-zih-energy/x86_energy/ ( 85f1a8b ). It should now write some error messages. Please report the output.

**Comment by kky-fury** [comment]
Dear @rschoene, Please find attached the output after the changes. It appears that there is an issue reading the cpus in parse_architecture.c (50-58)

[job_testing_ptf_after_changes.txt](https://github.com/score-p/scorep_plugin_x86_energy/files/2197605/job_testing_ptf_after_changes.txt)

**Comment by rschoene** [comment]
Dear @kky-fury, I pushed another patch. it seems like `strtol` does set `errno`, even though it should be able to read a number from the string `0-6,28-34`
I now explicitely set `errno` to `0` before calling `strtol`. Please try again.

**Comment by kky-fury** [comment]
Dear @rschoene, Thanks it works now.
